services:
  youtubepedia:
    container_name: youtubepedia
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DATABASE_URL
        - SMTP_HOST
        - SMTP_PORT
        - SMTP_USER
        - SMTP_PASS
        - PUBLIC_SITE_URL
        - SMTP_SERVICE
        - GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET
        - GROQ_API_KEY
    env_file: .env
    networks:
      - proxy
    ports:
      - '3001:3001' # Socket.IO port
      - '3000:3000' # Main app port
    labels:
      - 'traefik.enable=true'
      # Main application router
      - 'traefik.http.routers.youtubepedia.rule=Host(`youtubepedia.barron.agency`)'
      - 'traefik.http.routers.youtubepedia.entrypoints=websecure'
      - 'traefik.http.routers.youtubepedia.tls.certresolver=letsencrypt'
      - 'traefik.http.services.youtubepedia.loadbalancer.server.port=3000'

      # Socket.IO specific router
      - 'traefik.http.routers.youtubepedia-socket.rule=Host(`youtubepedia.barron.agency`) && PathPrefix(`/socket.io`)'
      - 'traefik.http.routers.youtubepedia-socket.entrypoints=websecure'
      - 'traefik.http.routers.youtubepedia-socket.service=youtubepedia-socket-service'
      - 'traefik.http.routers.youtubepedia-socket.tls.certresolver=letsencrypt'

      # Socket.IO service definition
      - 'traefik.http.services.youtubepedia-socket-service.loadbalancer.server.port=3001'

      # WebSocket middleware
      - 'traefik.http.middlewares.ws-middleware.headers.customrequestheaders.Connection=Upgrade'
      - 'traefik.http.middlewares.ws-middleware.headers.customrequestheaders.Upgrade=websocket'
      - 'traefik.http.routers.youtubepedia-socket.middlewares=ws-middleware'

networks:
  proxy:
    external: false
    name: proxy
