services:
  youtubepedia:
    container_name: youtubepedia
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DATABASE_URL
        - SMTP_HOST
        - SMTP_PORT
        - SMTP_USER
        - SMTP_PASS
        - PUBLIC_SITE_URL
        - SMTP_SERVICE
        - GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET
        - GROQ_API_KEY
    env_file: .env
    networks:
      - proxy
    ports:
      - '3001:3001' # Socket.IO port
      - '3000:3000' # Main app port
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.youtubepedia.rule=Host(`youtubepedia.barron.agency`)'
      - 'traefik.http.routers.youtubepedia.entrypoints=websecure'
      - 'traefik.http.routers.youtubepedia.tls.certresolver=letsencrypt'
      - 'traefik.http.services.youtubepedia.loadbalancer.server.port=3000'
      # WebSocket Middleware
      - 'traefik.http.middlewares.youtubepedia-ws.headers.customrequestheaders.Connection=Upgrade'
      - 'traefik.http.middlewares.youtubepedia-ws.headers.customrequestheaders.Upgrade=websocket'
      - 'traefik.http.routers.youtubepedia.middlewares=youtubepedia-ws'

networks:
  proxy:
    external: false
    name: proxy
