services:
  youtubepedia:
    container_name: youtubepedia
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_USER=${SMTP_USER}
        - SMTP_PASS=${SMTP_PASS}
        - PUBLIC_SITE_URL=${PUBLIC_SITE_URL}
        - SMTP_SERVICE=${SMTP_SERVICE}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - PUBLIC_SITE_URL=${PUBLIC_SITE_URL}
      - SMTP_SERVICE=${SMTP_SERVICE}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.youtubepedia.rule=Host(`youtubepedia.ai`)'
      - 'traefik.http.routers.youtubepedia.entrypoints=websecure'
      - 'traefik.http.routers.youtubepedia.tls.certresolver=letsencrypt'
      - 'traefik.http.services.youtubepedia.loadbalancer.server.port=3000'
networks:
  proxy:
    external: false
    name: proxy
