name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo SMTP_HOST=${{ secrets.SMTP_HOST }} >> .env
          echo SMTP_PORT=${{ secrets.SMTP_PORT }} >> .env
          echo SMTP_USER=${{ secrets.SMTP_USER }} >> .env
          echo SMTP_PASS=${{ secrets.SMTP_PASS }} >> .env
          echo PUBLIC_SITE_URL=${{ secrets.PUBLIC_SITE_URL }} >> .env
          echo SMTP_SERVICE=${{ secrets.SMTP_SERVICE }} >> .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
          echo GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} >> .env
          echo PUBLIC_SOCKET_URL=${{ secrets.PUBLIC_SITE_URL }} >> .env
          
      - name: Docker run
        run: docker compose up -d --force-recreate --build
